app.users:
    path: /user/list
    defaults: {_controller: 'AppBundle:User:index' }

app.user.add:
    path: /user/add
    defaults: {_controller: 'AppBundle:User:form', id: 0 }
    
app.user.edit:
    path: /user/{id}/edit
    defaults: {_controller: 'AppBundle:User:form' }
    requirements:
        id: \d+
        
app.user.remove:
    path: /user/{id}/remove/{confirmed}
    defaults: {_controller: 'AppBundle:User:remove', confirmed: 0 }
    requirements:
        confirmed: 0|1
        
app.auth.login:
    path: /auth/login
    defaults: {_controller: 'AppBundle:Auth:login' }
    
app.auth.check:
    path: /auth/check
    defaults: {_controller: 'AppBundle:Auth:check'}
    
    
app.auth.registration:
    path: /auth/registration
    defaults: {_controller: 'AppBundle:Auth/Registration:form' }
    
app.dashboard: 
    path: /dashboard
    defaults: {_controller: 'AppBundle:Dashboard:index' }