services:
  app.auth.registration:
    class: AppBundle\Auth\RegistrationService
    arguments: ["@doctrine.orm.default_entity_manager", "@event_dispatcher"]
  
  app.doctrine.craetedByuserEventListener:
        class: AppBundle\EventListener\Doctrine\CreatedByUserListener
        arguments: ["@security.token_storage"]
        tags:
            - { name: doctrine.event_subscriber, connection: default }