services:
#    app.example:
#        class: AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  app.auth.registration:
    class: AppBundle\Auth\RegistrationService
    arguments: ["@doctrine.orm.default_entity_manager", "@event_dispatcher"]