AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
      
    properties:
        name: 
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~
        password:
            - NotBlank: ~
        
        
AppBundle\Auth\Model\UserRegistration:
    properties:
        user:
            - Valid: {traverse: true}
        